import uuid
import logging
import asyncio
from datetime import datetime
from typing import List, Any
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlalchemy import select, update

from app.models import PipelineRun, AgentExecution, PipelineStatus, AgentStatus, Dataset
from app.schemas import PipelineRunCreate

logger = logging.getLogger(__name__)

class PipelineService:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def create_run(self, request: PipelineRunCreate) -> PipelineRun:
        # Fetch dataset to get name
        result = await self.db.execute(select(Dataset).where(Dataset.id == request.dataset_id))
        dataset = result.scalar_one_or_none()
        dataset_name = dataset.filename if dataset else "unknown.csv"
        
        logger.info(f"Pipeline run creating for dataset {request.dataset_id} ({dataset_name})")

        new_run = PipelineRun(
            id=uuid.uuid4(),
            dataset_id=uuid.UUID(request.dataset_id) if isinstance(request.dataset_id, str) else request.dataset_id,
            dataset_name=dataset_name,
            business_question=request.business_question,
            status=PipelineStatus.QUEUED,  # ✅ Passes the Enum object, PG_ENUM handles casting
            run_metadata={
                "hitl_agents": getattr(request, 'hitl_agents', []) or [],
                "custom_config": getattr(request, 'custom_config', {}) or {}
            }
        )
        
        self.db.add(new_run)
        await self.db.commit()
        await self.db.refresh(new_run)
        return new_run

    async def execute_pipeline_with_session(
        self, 
        run_id: uuid.UUID, 
        ws_manager: Any, 
        session_maker: async_sessionmaker
    ):
        """Background task that runs the 5 agents using a fresh, safe DB session."""
        async with session_maker() as db:
            try:
                # 1. Update Pipeline to RUNNING
                await db.execute(
                    update(PipelineRun).where(PipelineRun.id == run_id).values(status=PipelineStatus.RUNNING)
                )
                await db.commit()
                
                if ws_manager:
                    await ws_manager.broadcast(str(run_id), {"status": "running", "message": "Pipeline started"})

                # 2. Define the 5 Agents
                agents = ["data_engineer", "statistician", "ml_engineer", "designer", "strategist"]
                
                for agent_name in agents:
                    exec_id = uuid.uuid4()
                    
                    # Create execution record
                    agent_exec = AgentExecution(
                        id=exec_id,
                        run_id=run_id,
                        agent_name=agent_name,
                        status=AgentStatus.RUNNING,
                        started_at=datetime.utcnow()
                    )
                    db.add(agent_exec)
                    await db.commit()
                    
                    if ws_manager:
                        await ws_manager.broadcast(str(run_id), {"agent": agent_name, "status": "running"})

                    # --- AGENT WORK (Simulated for stability, replace with your LLM logic) ---
                    await asyncio.sleep(1) 
                    
                    mock_output = {
                        "agent": agent_name,
                        "insights": f"Strategic insights generated by {agent_name} for run {run_id}.",
                        "report": f"Executive summary for {agent_name}." if agent_name == "strategist" else None,
                        "charts": [{"chart_type": "bar_chart", "chart_data": [{"name": "Q1", "value": 45}, {"name": "Q2", "value": 62}]}] if agent_name == "designer" else []
                    }

                    # Update execution to COMPLETED
                    await db.execute(
                        update(AgentExecution).where(AgentExecution.id == exec_id).values(
                            status=AgentStatus.COMPLETED,
                            output_data=mock_output,
                            completed_at=datetime.utcnow(),
                            execution_time_ms=1000,
                            quality_score=95.0
                        )
                    )
                    await db.commit()
                    
                    if ws_manager:
                        await ws_manager.broadcast(str(run_id), {"agent": agent_name, "status": "completed"})

                # 3. Finalize Pipeline Run
                await db.execute(
                    update(PipelineRun).where(PipelineRun.id == run_id).values(
                        status=PipelineStatus.COMPLETED,
                        completed_at=datetime.utcnow(),
                        total_time_ms=5000,
                        quality_score_avg=95.0
                    )
                )
                await db.commit()
                
                if ws_manager:
                    await ws_manager.broadcast(str(run_id), {"status": "completed", "message": "Pipeline finished"})

            except Exception as e:
                logger.error(f"Pipeline {run_id} failed: {e}", exc_info=True)
                await db.execute(
                    update(PipelineRun).where(PipelineRun.id == run_id).values(status=PipelineStatus.FAILED)
                )
                await db.commit()
                if ws_manager:
                    await ws_manager.broadcast(str(run_id), {"status": "failed", "error": str(e)})

    async def get_history(self, limit: int = 20, offset: int = 0) -> List[PipelineRun]:
        result = await self.db.execute(
            select(PipelineRun).order_by(PipelineRun.started_at.desc()).offset(offset).limit(limit)
        )
        return result.scalars().all()

    async def get_status(self, run_id: uuid.UUID) -> dict:
        result = await self.db.execute(select(PipelineRun).where(PipelineRun.id == run_id))
        run = result.scalar_one_or_none()
        if not run:
            return None
            
        execs_result = await self.db.execute(
            select(AgentExecution).where(AgentExecution.run_id == run_id)
        )
        execs = execs_result.scalars().all()
        
        return {
            "run": run,
            "executions": execs,
            "progress_percent": (len([e for e in execs if e.status == AgentStatus.COMPLETED]) / 5) * 100
        }

    async def get_results(self, run_id: uuid.UUID) -> dict:
        result = await self.db.execute(select(PipelineRun).where(PipelineRun.id == run_id))
        run = result.scalar_one_or_none()
        if not run:
            return None
            
        execs_result = await self.db.execute(
            select(AgentExecution).where(AgentExecution.run_id == run_id)
        )
        execs = execs_result.scalars().all()
        
        executions_dict = {e.agent_name: e.output_data for e in execs}
        charts = []
        if "designer" in executions_dict and executions_dict["designer"]:
            charts = executions_dict["designer"].get("charts", [])
            
        return {
            "run": run,
            "executions": executions_dict,
            "charts": charts,
            "reports": []
        }

    async def get_logs(self, run_id: uuid.UUID) -> list:
        return [{"level": "info", "message": f"Execution logs for run {run_id}"}]
